### ISSUE TITLE
Wording for the "Proposal Status" needs to be changed

### ISSUE THREAD

**Issue by Boorclark** [BCStudentSoftwareDevTeam/celts#476] opened 2022-07-14 20:05 UTC
Currently, the SLC proposal status can be marked as completed, approved, or pending. This wording is confusing and needs to be changed to where they are all in the same tense. Approved is good, but pending and completed could use some rewording. 

------------------------------------------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/97637517/179073548-b38e77bc-ca86-4538-ad96-e7f8ff0c51ba.png)

**Comment by lodenrogue** [comment] 2022-07-14 21:36
Completed is past tense like approved. Not sure if pended sounds any better than pending. What did you have in mind?

**Comment by qasema** [comment] 2022-07-15 19:14
@lodenrogue  agree

**Comment by sheggen** [comment] 2022-07-15 19:52
The issue was worded poorly. The tense isn't the major issue. The issue is the fact that "Completed" doesn't convey what that means: the proposal is completed, or the approval process is completed? Same with Pending... is the proposal pending approval, or is the proposal incomplete (i.e., pending its own completion). 

There are three states of an SLC proposal that need captured with the correct term: 
1. the proposal has not been completed by the faculty member(s), and is in a saved state (pre-submitted)
2. the proposal has been completed by the faculty member(s), and is awaiting approval by CELTS staff
3. the proposal has been approved by the CELTS staff

**Comment by BrianRamsay** [comment] 2022-07-17 19:07
Currently on the whiteboard we have proposed these 3 statuses:

1 - Incomplete (also talked about In-Progress)
2 - Submitted
3 - Approved

**Comment by bledsoef** [comment] 2022-07-20 20:22
PR merged, closing issue.

**Closed as completed by bledsoef** 2022-07-20 20:22 UTC
